parameters:
#    synkedin.example.class: Fabsalito\SynkedinBundle\Example

services:
#    synkedin.example:
#        class: %synkedin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
